config/routes.rb
ShoppingHelper::Application.routes.draw do
  resources :list_items
  resources :lists
  resources :meals
  resources :food_feeds
  resources :users
  resources :sessions

  root "food_feeds#index"

  get "/meals/:id/add" => "meals#add_ingreds"
  post "/meals/:id/add" => "meals#save_new_ingreds"

  get "/endsession" => "sessions#destroy"

  get "/findusers" => "users#findusers"

  post "/follow" => "users#follow"

  get "/recipes/:id" => "meals#edit_ingreds"
  patch "/recipes/update/:id" => "meals#update_recipe"
  delete "/recipes/update/:id" => "meals#delete_recipe"

  delete "/users/follows/:id" => "users#delete_follows"

  get "/addmeals/:id" => "lists#add_meals"
  post "/addmeals/:id" => "lists#add_meal_to_list"

  get "/addingreds/lists/:id" => "lists#add_ingreds"
  get "/lists/edit/:id" => "lists#edit_ingreds"
  post "/add/lists/:id" => "lists#add_ingreds_to_list"
  post "/lists/:id" => "lists#show"
  delete "lists/edit/:id" => "lists#delete_ingred"
end

app/models/list.rb
class List < ActiveRecord::Base

	validates :name, :presence => true	

	belongs_to :user
	has_many :list_items, dependent: :destroy
end

app/controllers/lists_controller.rb
require 'open-uri'
require 'json'

class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  before_action :require_login, :except => [:home, :login]
  before_action :identify_user
  before_action :validate_creater, only: [:edit, :update, :destroy]

  # implement pagination .limit(#).offset(#)

  def validate_creater

    @list = List.find_by(:id => params[:id])

    if @list.user_id != session[:user_id]
      redirect_to root_url, notice: "You are not the creater!"
    end
  end

  def identify_user
    user = User.find_by(id: session[:user_id])
    if user
      @username = user.username
    end
  end

  def require_login
    if session[:user_id].blank?
      redirect_to root_url, notice: "You must login or sign up!"
    end
  end

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.where(:user_id => session[:user_id])
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    listid = params[:id]
    @list = List.find_by(:id => listid)
    @listitems = ListItem.where(:list_id => listid)

    # get direction info

    address = params[:address]
    city = params[:city]
    state = params[:state]

    if !params[:address].blank? & !params[:city].blank? & !params[:state].blank?
      origin = params[:origin]
      address = params[:address]
      city = params[:city]
      state = params[:state]

      data = findstore(origin, address, city, state)

      if data["status"] == "OK"
        @duration = format_trip_info(data["routes"].first["legs"].first["duration"].values_at("text"))
        @distance = format_trip_info(data["routes"].first["legs"].first["distance"].values_at("text"))
        @instructs = get_steps(data["routes"].first["legs"].first["steps"])
      end

    end
  end

  def edit_ingreds
    listid = params[:id]
    @list = List.find_by(:id => listid)
    @listitems = ListItem.where(:list_id => listid)
  end

  def delete_ingred
    listitem = ListItem.find_by(:id => params[:item_id])
    listitem.destroy

    redirect_to "/lists/edit/#{params[:id]}", notice: "Ingredient Deleted"
  end

  def findstore(base, address, city, state)
    origin = base
    origin = origin.gsub(' ', '+')

    destination = address + "+" + city + "+" + state
    destination = destination.gsub(' ', '+')

    url = "http://maps.googleapis.com/maps/api/directions/json?origin=#{origin}&destination=#{destination}&sensor=false"

    url = url.gsub("\n", '')

    json_data = open(url).read
    data = JSON.parse(json_data)
    return data

  end  

  def format_trip_info(trip_info)
      trip_info = trip_info.to_s
      trip_info = trip_info.gsub("[", "")
      trip_info = trip_info.gsub("]", "")
      trip_info = trip_info.gsub('"', "")

      return trip_info
  end

  def get_steps(steps)
      steps_size = (steps.length - 1)
      instructs = []

      for i in 0..steps_size
        newstep = steps[i].values_at("html_instructions").to_s
        newstep = newstep.gsub("[", "")
        newstep = newstep.gsub("]", "")
        newstep = newstep.gsub('"', "")

        newstep = CGI.escapeHTML(newstep)
        newstep = newstep.gsub(/&lt;[^&]*&gt;/, '')
        newstep = newstep.gsub(/&#39;/, "'")

        count = i + 1
        newstep = count.to_s + ". " + newstep

        instructs.push(newstep)
      end

      return instructs
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new
    @list.name = params[:name]
    @list.user_id = session[:user_id]


    if @list.save
      redirect_to "/addmeals/#{@list.id}", notice: 'List was successfully created.'
    else
      render action: 'new' 
    end
  end

  def add_meals
    @list = List.find_by(:id => params[:id])
    @list_items = ListItem.where(:list_id => @list.id)
    @meals = Meal.where(:user_id => [session[:user_id], session[:users_followed]])

  end

  def add_meal_to_list
    #need list
    list = List.find_by(:id => params[:id])
    list_items = ListItem.where(:list_id => list.id)

    recipes = Recipe.where(:meal_id => params[:meal])

    recipes.each do |recipe|
      ingred = Ingredient.find_by(:id => recipe.ingred_id)

      if list_items.find_by(:ingredient_id => ingred.id).blank?
        list_item = ListItem.new
        list_item.list_id = list.id
        list_item.ingredient_id = ingred.id
        list_item.save
      end
    end

    redirect_to "/addmeals/#{list.id}"

  end

  def add_ingreds
  end

  def add_ingreds_to_list
    list = List.find_by(:id => params[:id])
    list_items = ListItem.where(:list_id => list.id)

    ingreds = [ params[:ingred1], params[:ingred2], params[:ingred3], 
      params[:ingred4], params[:ingred5], params[:ingred6], params[:ingred7],
        params[:ingred8], params[:ingred9], params[:ingred10] ]

    for i in 0..9
      if ingreds[i].blank?
        break
      end

      #check if Ingredient already in database
      #if not, create new ingredient

      ingredname = Ingredient.find_by(:name => ingreds[i].downcase)

      if ingredname.blank?
        @ingred = Ingredient.new
        @ingred.name = ingreds[i].downcase
        @ingred.save
      else
        @ingred = ingredname
      end

      #check if ingred already in list

      check_list = list_items.where(:ingredient_id => @ingred.id)

      if check_list.blank?
        listitem = ListItem.new
        listitem.ingredient_id = @ingred.id
        listitem.list_id = list.id
        listitem.save
      end
    end

    redirect_to lists_path, notice: "List successfully updated"      
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    if @list.update(list_params)
      @list.name = params[:name]
      @list.save

      redirect_to "/addmeals/#{@list.id}", notice: 'List was successfully updated.'
    else
      render action: 'edit' 
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    redirect_to lists_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params[:list]
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, "#{@list.name}" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/add_ingreds.html.erb
<h1>Add Ingredients to List</h1>

<%= form_tag "/add/lists/#{params[:id]}", :method => 'post' do %>
	<% for i in 1..10 %>
		<% ingredsym = "ingred" + i.to_s %>

		<div class="field">
		  <%= label_tag "#{ingredsym}" %>
		  <%= text_field_tag "#{ingredsym}" %>
		</div>	
		<br>
	<% end %>
	<div class="actions">
		<%= submit_tag "Save New Ingredients" %>
	</div>
	<br>
<% end %>

app/views/lists/add_meals.html.erb
<h1>Add Meals To List</h1>

<% if @list_items.blank? %>
	<%= "No items added to list" %>
<% else %>
	<h3>Items added:</h3>
	<% @list_items.each do |list_item| %>
		<p><%= Ingredient.find_by(:id => list_item.ingredient_id).name %></p>
	<% end %>
<% end %>

<%= button_to "Add additional ingredients", "/addingreds/lists/#{@list.id}", method: :get %><br>

<h3>Meals you can add</h3>
<% @meals.each do |meal| %>
    <p><b><%= link_to meal.name, meal_path(meal.id) %></b></p>
	<p><b><%= image_tag meal.image, size:"210x163" %></b></p>

    <p><%= button_to 'Add Meal to List', "/addmeals/#{@list.id}?meal=#{meal.id}", method: :post %></p>
    <br>
<% end %>

<%= link_to 'Back', "/lists/#{params[:id]}" %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %><br>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', "/lists/#{params[:id]}" %>

app/views/lists/edit_ingreds.html.erb
<h1>Edit List Ingredients</h1>

<ul>
	<% @listitems.each do |item| %>
		<li><%= Ingredient.find_by(:id => item.ingredient_id).name %>
			<%= button_to "Delete Ingredient", "#{@list.id}?item_id=#{item.id}", method: :delete %></li><br>
	<% end %>
</ul>

<%= link_to 'Back', "/lists/#{params[:id]}" %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<%= button_to 'Create New List', new_list_path, method: :get %><br>

<% @lists.each do |list| %>
    <p><strong><%= link_to list.name, "/lists/#{list.id}" %></strong></p>
    <p><%= link_to 'Show', list %> | 
    <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/lists/new.html.erb
<h1>New Grocery List</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul>
	<% @listitems.each do |item| %>
		<li><%= Ingredient.find_by(:id => item.ingredient_id).name %></li>
	<% end %>
</ul>

<%= link_to 'Edit Main Info', edit_list_path(@list) %> |
<%= link_to 'Add Ingredients', "/addmeals/#{@list.id}" %> |  
<%= link_to 'Edit Ingredients', "/lists/edit/#{@list.id}" %> | 
<%= link_to 'Back', lists_path %>

<h3>Directions to Store</h3>

<% if !@instructs.blank? %>
  <%= @duration %>
  <%= @distance %>
  <br><br>

  <% @instructs.each do |step| %>
  	<%= step %>
  	<br>
  <% end %>
  <br>
<% end %>

<%= form_tag "/lists/#{@list.id}", method: :post do %>
  <div class="field">
    <%= label_tag :origin %><br>
    <input type="radio" name=<%= :origin %> value="1800 West Lawrence Avenue Chicago IL 60640" checked>Mariano's-Ravenswood<br>
    <input type="radio" name=<%= :origin %> value="3350 N Western Ave Chicago IL 60618">Mariano's-Roscoe Village<br>
    <input type="radio" name=<%= :origin %> value="3300 N. Ashland Ave Chicago  Illinois  60657">Whole Foods-Lakeview
  </div><br>
  <div class="field">
    <%= label_tag :address %><br>
    <%= text_field_tag :address %>
  </div>
  <div class="field">
    <%= label_tag :city %><br>
    <%= text_area_tag :city %>
  </div>
  <div class="field">
    <%= label_tag :state %><br>
    <%= text_field_tag :state %>
  </div><br>
  <div class="actions">
    <%= submit_tag "Find directions!" %>
  </div>
<% end %>