config/routes.rb
ShoppingHelper::Application.routes.draw do
  resources :list_items
  resources :lists
  resources :meals
  resources :food_feeds
  resources :users
  resources :sessions

  root "food_feeds#index"

  get "/meals/:id/add" => "meals#add_ingreds"
  post "/meals/:id/add" => "meals#save_new_ingreds"

  get "/endsession" => "sessions#destroy"

  get "/findusers" => "users#findusers"

  post "/follow" => "users#follow"

  get "/recipes/:id" => "meals#edit_ingreds"
  patch "/recipes/update/:id" => "meals#update_recipe"
  delete "/recipes/update/:id" => "meals#delete_recipe"

  delete "/users/follows/:id" => "users#delete_follows"

  get "/addmeals/:id" => "lists#add_meals"
  post "/addmeals/:id" => "lists#add_meal_to_list"

  get "/addingreds/lists/:id" => "lists#add_ingreds"
  get "/lists/edit/:id" => "lists#edit_ingreds"
  post "/add/lists/:id" => "lists#add_ingreds_to_list"
  post "/lists/:id" => "lists#show"
  delete "lists/edit/:id" => "lists#delete_ingred"
end

app/models/meal.rb
class Meal < ActiveRecord::Base

	validates :name, :presence => true

	belongs_to :user
	has_many :ingredients, through: :recipes, foreign_key: :ingred_id
	has_many :recipes, dependent: :destroy
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  before_action :require_login, :except => [:home, :login]
  before_action :identify_user
  before_action :validate_creater, only: [:edit, :update, :destroy, :edit_ingreds, 
      :add_ingreds, :save_new_ingreds ]

  # implement pagination .limit(#).offset(#)

  def validate_creater

    @meal = Meal.find_by(:id => params[:id])

    if @meal.user_id != session[:user_id]
      redirect_to root_url, notice: "You are not the creater!"
    end
  end

  def identify_user
    user = User.find_by(id: session[:user_id])
    if user
      @username = user.username
    end
  end

  def require_login
    if session[:user_id].blank?
      redirect_to root_url, notice: "You must login or sign up!"
    end
  end

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.where(:user_id => session[:user_id]).order("created_at desc")

    @friend_meals = Meal.where(:user_id => session[:users_followed])
  end

  # GET /meals/1
  # GET /meals/1.json
  def show

    @ingreds = Recipe.where(:meal_id => params[:id])

  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
    @recipes = Recipe.where(:meal_id => params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)
    @meal.user_id = session[:user_id]

    if @meal.save
      redirect_to "/meals/#{@meal.id}/add", notice: 'Meal was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def edit_ingreds
    @recipes = Recipe.where(:meal_id => params[:id])
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    if @meal.update(meal_params)
      @meal.user_id = session[:user_id]
      redirect_to "/recipes/#{@meal.id}", notice: 'Meal was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  def update_recipe
    @recipes = Recipe.where(:meal_id => params[:id])

    @recipes.each do |recipe|
      recipeid = recipe.id.to_s
      recipe.measure = params[recipeid]
      recipe.save
    end

    redirect_to meals_path, notice: "Recipe successfully updated"
  end

  def delete_recipe
    recipeid = params[:recipeid].to_i
    dele_recipe = Recipe.find_by(:id => recipeid)
    dele_recipe.destroy

    redirect_to meals_path, notice: "Recipe successfully updated"    
  end

  def add_ingreds
  end

  def save_new_ingreds
    ingreds = [ params[:ingred1], params[:ingred2], params[:ingred3], 
      params[:ingred4], params[:ingred5], params[:ingred6], params[:ingred7],
        params[:ingred8], params[:ingred9], params[:ingred10] ]
    measures = [ params[:measure1], params[:measure2], params[:measure3], 
      params[:measure4], params[:measure5], params[:measure6], params[:measure7],
        params[:measure8], params[:measure9], params[:measure10] ]

    for i in 0..9
      if ingreds[i].blank?
        break
      end

      #check if Ingredient already in database
      #if not, create new ingredient

      ingredname = Ingredient.find_by(:name => ingreds[i].downcase)

      if ingredname.blank?
        @ingred = Ingredient.new
        @ingred.name = ingreds[i].downcase
        @ingred.save

      else
        @ingred = ingredname

      end
        recipe = Recipe.new
        recipe.ingred_id = @ingred.id
        recipe.meal_id = params[:id]
        recipe.measure = measures[i]
        recipe.save

    end

    redirect_to meals_path, notice: "Recipe successfully updated"  
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    redirect_to meals_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :description, :image, :url, :user_id)
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %> -- to save image, right-click image and choose <strong>'Copy Image URL'</strong><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :url %> -- save the location of this recipe so you don't have to search for it later!<br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/meals/add_ingreds.html.erb
<h1>Add Ingredients</h1>

<%= form_tag "/meals/#{params[:id]}/add", :method => 'post' do %>
	<% for i in 1..10 %>
		<% ingredsym = "ingred" + i.to_s %>
		<% measuresym = "measure" + i.to_s %>

		<div class="field">
		  <%= label_tag "#{ingredsym}" %>
		  <%= text_field_tag "#{ingredsym}" %>
		</div>	
		<div class="field">
		  <%= label_tag "#{measuresym}" %>
		  <%= text_field_tag "#{measuresym}" %>
		</div>	
		<br>
	<% end %>
	<div class="actions">
		<%= submit_tag "Save New Ingredients" %>
	</div>
	<br>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %><br>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/edit_ingreds.html.erb
<h1>Edit Ingredients</h1>

<%= button_to "Add more ingredients", "/meals/#{params[:id]}/add", method: :get %>

<%= form_tag "/recipes/update/#{params[:id]}", :method => 'patch' do %>
	<% @recipes.each do |recipe| %>
		<% @ingred = Ingredient.find_by(:id => recipe.ingred_id) %>
		<div class="field">
		  <h3><%= @ingred.name %></h3>
		</div>	
		<div class="field">
		  <%= label_tag :measure %>
		  <%= text_field_tag "#{recipe.id}", recipe.measure %>
		  <%= link_to 'Delete?', "/recipes/update/#{params[:id]}?recipeid=#{recipe.id}", method: :delete %>
		</div>
	<% end %>
		<div class="actions">
			<%= submit_tag "Save Changes" %>
		</div><br>	
<% end %>	

<%= link_to "Back", "/meals/#{params[:id]}" %>

app/views/meals/index.html.erb
<h1>Meals</h1>

    <%= button_to 'Create New Meal/Recipe', new_meal_path, method: :get %><br>

    <% @meals.each do |meal| %>
        <p><b><%= link_to meal.name + " (see recipe)", meal_path(meal.id) %>           <% if !meal.url.blank? %>
                -- <%= link_to "link to meal source", meal.url %></b>
            <% end %></p>
            
        <p><%= meal.description %></p> 

        <% if !meal.image.blank? %>     
            <p><%= image_tag meal.image, size:"420x325"%></p>
        <% end %>

        <p><%= link_to 'Edit Main Info', edit_meal_path(meal) %> | <%= link_to 'Edit Ingredients', "/recipes/#{meal.id}" %> | 
            <%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></p><br>
    <% end %>

    <h3>Food Friend meals:</h3>

    <% @friend_meals.each do |meal| %>
    	<% user = User.find_by(:id => meal.user_id) %>
    	<p>Created by <%= user.username %>: <b><%= link_to meal.name + " (see recipe)", meal_path(meal.id) %> 

        <% if !meal.url.blank? %>
            -- <%= link_to "link to meal source", meal.url %></b>
        <% end %></p>

        <p><%= meal.description %></p>

        <% if !meal.image.blank? %>
            <p><%= image_tag meal.image, size:"420x325"%></p>
        <% end %><br>

    <% end %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p><strong><%= @meal.name + " - " + @meal.description %></strong></p>

<p><% @ingreds.each do |ingred| %>
		<%= Ingredient.find_by(:id => ingred.ingred_id).name %>- 
		<%= ingred.measure %>
		<br>
	<% end %></p>

<p><%= image_tag @meal.image %></p>

<p><% if @meal.user_id == session[:user_id] %>
		<%= link_to 'Edit', edit_meal_path(@meal) %> | 
	<% end %>
	<%= link_to 'Back', meals_path %></p>