config/routes.rb
ShoppingHelper::Application.routes.draw do
  resources :list_items
  resources :lists
  resources :meals
  resources :food_feeds
  resources :users
  resources :sessions

  root "food_feeds#index"

  get "/meals/:id/add" => "meals#add_ingreds"
  post "/meals/:id/add" => "meals#save_new_ingreds"

  get "/endsession" => "sessions#destroy"

  get "/findusers" => "users#findusers"

  post "/follow" => "users#follow"

  get "/recipes/:id" => "meals#edit_ingreds"
  patch "/recipes/update/:id" => "meals#update_recipe"
  delete "/recipes/update/:id" => "meals#delete_recipe"

  delete "/users/follows/:id" => "users#delete_follows"

  get "/addmeals/:id" => "lists#add_meals"
  post "/addmeals/:id" => "lists#add_meal_to_list"

  get "/addingreds/lists/:id" => "lists#add_ingreds"
  get "/lists/edit/:id" => "lists#edit_ingreds"
  post "/add/lists/:id" => "lists#add_ingreds_to_list"
  post "/lists/:id" => "lists#show"
  delete "lists/edit/:id" => "lists#delete_ingred"
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base

	has_many :ingredients
	belongs_to :list
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    if @list_item.save
      redirect_to @list_item, notice: 'List item was successfully created.' 
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    if @list_item.update(list_item_params)
      redirect_to @list_item, notice: 'List item was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    redirect_to list_items_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params[:list_item]
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<h1>Listing list_items</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= link_to 'Show', list_item %></td>
        <td><%= link_to 'Edit', edit_list_item_path(list_item) %></td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>New list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>