config/routes.rb
ShoppingHelper::Application.routes.draw do
  resources :list_items
  resources :lists
  resources :meals
  resources :food_feeds
  resources :users
  resources :sessions

  root "food_feeds#index"

  get "/meals/:id/add" => "meals#add_ingreds"
  post "/meals/:id/add" => "meals#save_new_ingreds"

  get "/endsession" => "sessions#destroy"

  get "/findusers" => "users#findusers"

  post "/follow" => "users#follow"

  get "/recipes/:id" => "meals#edit_ingreds"
  patch "/recipes/update/:id" => "meals#update_recipe"
  delete "/recipes/update/:id" => "meals#delete_recipe"

  delete "/users/follows/:id" => "users#delete_follows"

  get "/addmeals/:id" => "lists#add_meals"
  post "/addmeals/:id" => "lists#add_meal_to_list"

  get "/addingreds/lists/:id" => "lists#add_ingreds"
  get "/lists/edit/:id" => "lists#edit_ingreds"
  post "/add/lists/:id" => "lists#add_ingreds_to_list"
  post "/lists/:id" => "lists#show"
  delete "lists/edit/:id" => "lists#delete_ingred"
end

app/models/food_feed.rb
class FoodFeed < ActiveRecord::Base

	validates :title, :presence => true

	belongs_to :user

	after_create :check_video
	after_create :populate_url
	after_create :populate_image

	def check_video
		# if url.blank and !image.blank, assume user put url in wrong location
		if self.feed_type == "video"
			check_video_url
			check_url_format
			self.image = "http://www.standwithus.com/images/Play-icon2.png"
		end

		self.save
	end

	def check_video_url
		# if url.blank and !image.blank, assume user put url in wrong location
		if self.url.blank? && !self.image.blank?
			self.url = self.image
			self.image = ""
			# self.save
		# if both field blanks, copy default video
		elsif (self.url.blank? && self.image.blank?) || !self.url.include?("youtu")
			self.url = "//www.youtube.com/embed/kATDHi2M32Y"
			# self.save
		end
	end

	def check_url_format
		if !self.url.include?("embed")
			# self.url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
			# youtube_id = $5
			# self.url = "//www.youtube.com/embed/#{ youtube_id }"
			if self.url[/youtu\.be\/([^\?]*)/]
				youtube_id = $1
			else
			    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
			    self.url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
			    youtube_id = $5
			end		
				
			self.url = "//www.youtube.com/embed/#{ youtube_id }"
		end

		if !self.url.start_with?("//")
			self.url = "//" + self.url
		end

		# self.save
	end

	def populate_url
		if self.url.blank? && (self.feed_type == "article") 
			self.url = "http://www.goodreads.com/author/quotes/1124.Anthony_Bourdain"
			self.save	
		end
	end

	def populate_image
		if self.image.blank? && (self.feed_type == "article" || self.feed_type == "image")
			self.image = "http://www.livingwithjuvenilearthritis.com/wp-content/uploads/2013/12/Spam-Can.jpg"
			self.save
		end
	end
end

app/controllers/food_feeds_controller.rb
class FoodFeedsController < ApplicationController
  before_action :set_food_feed, only: [:show, :edit, :update, :destroy]

  before_action :require_login, :except => [:home, :login]
  before_action :identify_user
  before_action :validate_creater, only: [:edit, :update, :destroy]

  # implement pagination .limit(#).offset(#)

  def validate_creater

    @food_feed = FoodFeed.find_by(:id => params[:id])

    if @food_feed.create_user_id != session[:user_id]
      redirect_to root_url, notice: "You are not the creater!"
    end
  end

  def identify_user
    user = User.find_by(id: session[:user_id])
    if user
      @username = user.username
    end
  end

  def require_login
    if session[:user_id].blank?
      render "welcome", notice: "You must login or sign up!"
    end
  end

  # GET /food_feeds
  # GET /food_feeds.json
  def index 
    @food_feeds = FoodFeed.where(:create_user_id => [session[:users_followed], session[:user_id]]).order("created_at desc")
  end

  # GET /food_feeds/1
  # GET /food_feeds/1.json
  def show
  end

  # GET /food_feeds/new
  def new
    @food_feed = FoodFeed.new
  end

  # GET /food_feeds/1/edit
  def edit
  end

  # POST /food_feeds
  # POST /food_feeds.json
  def create
    @food_feed = FoodFeed.new(food_feed_params)

    @food_feed.feed_type = params[:feed_type]
    @food_feed.create_user_id = session[:user_id]

    if @food_feed.save
        redirect_to food_feeds_path, notice: 'Food feed was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /food_feeds/1
  # PATCH/PUT /food_feeds/1.json
  def update
    if @food_feed.update(food_feed_params)
      @food_feed.feed_type = params[:feed_type]
      @food_feed.save
      redirect_to @food_feed, notice: 'Food feed was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  # DELETE /food_feeds/1
  # DELETE /food_feeds/1.json
  def destroy
    @food_feed.destroy
    redirect_to food_feeds_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_feed
      @food_feed = FoodFeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_feed_params
      params.require(:food_feed).permit(:title, :description, :url, :image)
    end
end

app/helpers/food_feeds_helper.rb
module FoodFeedsHelper
end

app/views/food_feeds/_form.html.erb
<%= form_for(@food_feed) do |f| %>
  <% if @food_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_feed.errors.count, "error") %> prohibited this food_feed from being saved:</h2>

      <ul>
      <% @food_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_type %><br>
    <input type="radio" name=<%= :feed_type %> value="article" checked>Article<br>
    <input type="radio" name=<%= :feed_type %> value="image">Image<br>
    <input type="radio" name=<%= :feed_type %> value="video">Video
  </div><br>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %> -- if <strong>video</strong>, put Youtube URL here!<br>
    <%= f.text_field :url %>
  </div>
  <div class="field"> 
    <%= f.label :image %> -- to save <strong>image</strong>, right-click image and choose <strong>'Copy Image URL'</strong><br>
    <%= f.text_field :image %>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_feeds/edit.html.erb
<h1>Edit Food Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_feed %> |
<%= link_to 'Back', food_feeds_path %>

app/views/food_feeds/index.html.erb
<h1>Food Feed</h1>
<p><%= button_to 'Create New Food Feed', new_food_feed_path, method: :get %></p><br>


    <% @food_feeds.each do |food_feed| %>
    	<% if food_feed.create_user_id != session[:user_id] %>
    		<p><%= User.find_by(:id => food_feed.create_user_id).username %> posted:</p>
    	<% end %>
        <% if food_feed.feed_type == "video" %>
        	<p><strong><%= food_feed.title %></strong></p>
        	<p><iframe width="420" height="325" src="<%= food_feed.url %>" allowfullscreen></iframe></p>
        <% elsif food_feed.feed_type == "image" %>
        	<p><strong><%= food_feed.title %></strong></p>
        	<p><%= image_tag food_feed.image, size: "420x325" %></p>        
        <% else %> 
        	<p><%= link_to food_feed.title, food_feed.url %></p>
        	<p><%= image_tag food_feed.image, size: "420x325" %></p>
        <% end %>
        <p><%= food_feed.description %></p>
        <% if food_feed.create_user_id == session[:user_id] %>
	        <p><%= link_to 'Delete FoodFeed', food_feed, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	   	<% end %>
    <% end %>

<br>

<p><%= button_to 'Create New Food Feed', new_food_feed_path, method: :get %></p><br>

app/views/food_feeds/new.html.erb
<h1>Post New Food Feed</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', food_feeds_path %>

app/views/food_feeds/show.html.erb
<br><br>
<p><strong><%= @food_feed.feed_type %></strong></p>

<p><%= @food_feed.title %></p>
<p><%= @food_feed.description %></p>
<p><%= link_to @food_feed.url %></p>
<p><%= image_tag @food_feed.image, size: "420x325" %></p>

<%= link_to 'Edit', edit_food_feed_path(@food_feed) %> |
<%= link_to 'Back', food_feeds_path %>

app/views/food_feeds/welcome.html.erb
<h1>Welcome to ShopperHelper</h1>

<p>ShopperHelper was created to mitigate the downsides of cooking (except cleaning dishes!) by 
	making it easy to save recipes, plan meals, and get in and out of the
	supermarket</p>

<h3><strong>To begin, <%= link_to "log in", "/sessions" %> or 
	<%= link_to "sign up", "/users" %>!</strong></h3>